const fs=require('fs');
const P={
'make-jw.js':{h:"New here? The story in ninety seconds",p:`<p><b>In 1879 a Pittsburgh haberdasher named Charles Taze Russell began publishing a magazine called <i>Zion's Watch Tower</i>.</b> He taught that Christ had already returned invisibly — in 1874 — and that 1914 would bring the end of the present world order. When 1914 came and brought a world war instead of Armageddon, the date was kept and its meaning was changed: it now marked Christ's invisible enthronement rather than the end.</p>
    <p>His successor <b>Joseph Rutherford</b>, a lawyer, took control after Russell's death in 1916, gave the movement its name in 1931, predicted the resurrection of Abraham, Isaac and Jacob by 1925, and built <b>Beth Sarim</b>, a San Diego mansion deeded to them. Later leaders added 1975. Each failure was absorbed rather than admitted.</p>
    <p><b>The chain that holds everything together runs 607 → 1914 → 1919 → the Governing Body.</b> The organization dates Jerusalem's destruction to 607 BC, adds 2,520 years to reach 1914, and teaches that in 1919 Christ inspected all religions and appointed the Watch Tower Society over his belongings. That appointment is the basis of the Governing Body's authority — and therefore of the blood doctrine, the shunning policy, and the obligation to accept every future adjustment.</p>
    <p>Along the way the organization produced its own Bible, the <b>New World Translation</b>, from an anonymous committee. Names and terms in dotted underline can be hovered anywhere for a definition.</p>`},
'make-bhi.js':{h:"New here? The story in ninety seconds",p:`<p><b>The core claim is that Black, Hispanic and Native Americans are the literal descendants of the twelve tribes of Israel</b> — and that the people known as Jews today are not. The argument runs almost entirely through one chapter: <b>Deuteronomy 28</b>, the covenant curses, and especially verse 68, which says the LORD will bring Israel back to Egypt in ships to be sold as slaves. Read as a prophecy of the transatlantic slave trade, the chapter appears to describe African-American history in detail.</p>
    <p>Attached to it is a <b>12 Tribes Chart</b> mapping each tribe onto a modern nationality, and a doctrine identifying <b>Esau</b> and <b>Edom</b> with white people. Salvation, in the strongest camp teaching, is bounded by descent and by law-keeping.</p>
    <p><b>This is not one organization, and that matters enormously.</b> It runs from the Church of God and Saints of Christ — founded in 1896 by William Saunders Crowdy, born enslaved, a Union Army veteran, and still a functioning denomination — through a vegan farming community at <b>Dimona</b> in Israel, to the confrontational street camps of the viral videos. They disagree with each other bitterly. Any argument that treats them as a single thing fails immediately.</p>
    <p>And underneath all of it is a real grievance: the church was largely silent about slavery, and often worse. Names and terms in dotted underline can be hovered anywhere for a definition.</p>`},
'make-messiah.js':{h:"New here? What this section is actually arguing",p:`<p><b>This section runs in the opposite direction from the rest of the site.</b> Everywhere else, the Bible is the shared standard and a movement's claims are weighed against it. Here the New Testament is not shared ground — so the case is made from the <b>Tanakh</b> (the Hebrew Bible), from the <b>Targum</b>, and from the <b>Talmud</b>: sources a Jewish friend already holds.</p>
    <p><b>The central problem is that the Hebrew Scriptures give two portraits</b> of the one to come: a conquering king of David's line, and a servant who is despised, pierced and killed (Isaiah 53). These look irreconcilable — and the rabbis saw it too. <b>Sukkah 52a</b> resolves it with two Messiahs: Messiah ben Joseph, who is slain, and Messiah ben David, who reigns. The Christian claim is smaller than it sounds: not two figures, but one, twice.</p>
    <p>Alongside that sit two datable arguments. <b>Daniel 9</b> has an anointed one cut off <i>before</i> the Temple is destroyed — and the Temple fell in AD 70. And <b>Yoma 39b</b>, in the Talmud itself, records that for the forty years before that destruction the Yom Kippur signs failed. Forty years before 70 is AD 30.</p>
    <p><b>None of it can be said until something else is.</b> The Crusades, the blood libel, the expulsions, forced disputations, Luther, and the <b>Shoah</b> — that history is the room this conversation happens in, and it must be named first and unprompted. Terms in dotted underline can be hovered anywhere for a definition.</p>`},
'make-god.js':{h:"New here? How this section works",p:`<p><b>This section runs in the opposite direction from the rest of the site.</b> Nothing here is argued from biblical authority to someone who does not hold it. Instead the case is built from sources that do not want the conclusion — skeptical historians, atheist philosophers, and the manuscript and archaeological record.</p>
    <p><b>The first thing to get right is who you are talking to.</b> The <i>philosophical atheist</i> is rare, has genuine reasons, reads Graham Oppy and Sean Carroll, and enjoys a well-conducted argument. The <i>apathetic none</i> is the large majority, is not looking for an argument at all, and is reachable mostly through relationship. The <i>deconvert</i> was a Christian, has already heard your best material — usually from people they loved — and often carries a real injury from the church. Aiming the wrong conversation at the wrong person is the most common way this fails.</p>
    <p><b>The realistic goal is one notch, not the whole distance:</b> from "obviously false" to "actually worth thinking about." The arguments here are cumulative rather than knockdown — contingency, fine-tuning, moral facts, the reliability of reason — and each has a serious reply, which is printed alongside it.</p>
    <p>A third of this section is marked <b>Contested</b> on purpose, and five entries are arguments to <b>retire</b>. Overclaiming is how these conversations are lost. Terms in dotted underline can be hovered anywhere for a definition.</p>`}
};
for(const [f,pr] of Object.entries(P)){
  let s=fs.readFileSync(__dirname+'/'+f,'utf8');
  if(s.includes('const PRIMER =')) { console.log('skip',f); continue; }
  s=s.replace('\nbuild({', '\nconst PRIMER = '+JSON.stringify(pr)+';\n\nbuild({');
  s=s.replace('  GLOSSARY: MERGED,', '  GLOSSARY: MERGED, primer: PRIMER,');
  fs.writeFileSync(__dirname+'/'+f,s);
  console.log('primer added to',f);
}
