const g=require('./grade.js');
const T={};
T.full_claim="Joseph Smith published Facsimile 1 as a picture of Abraham. He labelled the man on the couch as Abraham 'fastened upon an altar,' and the standing figure as 'the idolatrous priest of Elkenah' about to kill him. Egyptologists identify the same drawing at a glance. It is a lion-couch vignette — a standard funeral scene showing the jackal-headed god Anubis tending the mummy of Osiris. The original survives as Papyrus Joseph Smith I, part of a Book of Breathings made for a Theban priest named Hor around the second century BC, roughly 1,500 years after Abraham lived. There is one complication, and it is the heart of the argument. The papyrus has a hole in it, and the hole sits exactly where the priest's head and knife appear in the 1842 printed version. That printed version was drawn by a woodcut artist, not preserved on the papyrus. Robert Ritner and other Egyptologists point to ink traces of a headdress at the shoulder, which fits a jackal head rather than a bald human one. No other lion-couch scene anywhere shows a knife. Smith's other labels on the same drawing fare worse: he calls the bird the Angel of the Lord, the four canopic jars the idolatrous gods of foreign nations, and the crocodile the idolatrous god of Pharaoh. None of those match any accepted Egyptological reading.";
T.full_response="Egyptologist John Gee, Kerry Muhlestein and Pearl of Great Price Central make four arguments. First, the hole means nobody knows what was there. Some argue the papyrus was already damaged in 1835, so a knife and a human head could have filled the gap — and they note this vignette is genuinely unusual, since the figure on the couch appears clothed, alive, and possibly with both hands raised. Second, Egyptian temple scenes do depict the ritual killing of enemies, so reading a sacrifice here is not absurd on its face. Third, on the 'Semitic adaptation' theory, Jews living in Egypt demonstrably reused Egyptian art and gave it new meaning — Abraham's name appears in later Egyptian magical papyri — so the drawing could have illustrated an Abraham text whatever its funeral origin. Fourth, some argue the Book of Abraham was revealed rather than translated, with the papyri acting only as a prompt. On that view the facsimile explanations are inspired commentary, not Egyptology, and comparing them to Egyptology misses the point.";
T.full_rationale="Facsimile 1 differs from the other two, and that difference is why this is graded contested. Here there is a real gap in the evidence: the hole covers exactly the disputed parts, so the argument runs on parallels and faint ink traces rather than on a surviving original. The scholarly reading is far better supported. There are headdress traces at the shoulder, hundreds of parallel funeral scenes, and not one parallel showing a knife. The church's own Gospel Topics essay concedes that Egyptologists read the facsimiles differently from Joseph Smith. But the defenders are disputing what filled the hole rather than disputing the Egyptology itself, and the vignette does have odd features. That is enough to keep this figure at contested. It is worth adding that the surrounding labels — canopic jars as foreign gods, crocodile as Pharaoh's god — have no Egyptological support at all, and those are not covered by any hole.";
T.plain="**What Joseph Smith said.** The Book of Abraham prints three Egyptian drawings with his explanations. In the first one, he said the man lying down is Abraham, tied to an altar. He said the man standing over him is a pagan priest about to kill him.\n\n**What the drawing actually is.** Egyptologists recognise this scene right away. It is a funeral picture. The dog-headed god Anubis is preparing a body for burial. Hundreds of the same scene survive. This one was made for an Egyptian priest named Hor, about 1,500 years after Abraham lived.\n\n**The catch.** There is a hole in the papyrus. It sits right where the priest's head and knife are shown in the printed version. So we cannot see the original for those two things. An artist drew them in for the 1842 printing.\n\n**How sure are we?** Fairly, but not completely. Scholars point to faint ink marks of a headdress, which fits a dog head, not a bald man. And no other picture like this has a knife in it. But because the hole covers the exact spot, we grade this one contested rather than settled.\n\n**Why it matters.** The rest of the labels have no hole to hide behind. He called four jars the gods of foreign nations, and a crocodile the god of Pharaoh. Egyptologists say those readings are simply wrong. The church now admits its scholars read these drawings differently than he did.\n\n**What to say.** Ask one question: \"Can we look at what the Egyptologists say about the parts that are not damaged?\"";
const orig={claim:376,response:210,rationale:200};
console.log('field'.padEnd(12)+'  grade   words   w/sent  longest sentence');
for(const [k,v] of Object.entries(T)){const r=g(v);
  console.log(k.padEnd(12)+String(r.grade).padStart(6)+String(r.words).padStart(8)+String(r.wps).padStart(9)+String(r.longest).padStart(9));}
require('fs').writeFileSync('demo-text.json',JSON.stringify(T,null,1));
