const fs=require('fs'),g=require('./grade.js');
const T={
 mormon:[
  {icon:"🔍",title:"What this is",body:"<b>__N__ documented claims</b> about the Latter-day Saint church, each weighed against the Bible. Every case gives the strongest LDS answer first, then an honest verdict. Popular Christian arguments that fail are marked <b>do not use</b> — there are nine of them here."},
  {icon:"📖",title:"Every case opens in plain English",body:"Short blocks. One idea per sentence. What they teach, what the text says, their best answer, how strong it is, and one line to actually say out loud. The sourced version — scholars named, citations in full — sits underneath on the same page. Nothing is hidden."},
  {icon:"🏷",title:"Four verdicts, one glance",body:"Every claim lands in one of four columns:<div class=\"vrow2\"><div><span class=\"badge v-admitted\">Admitted</span><span>the church's own publications concede it</span></div><div><span class=\"badge v-unrefuted\">Unrefuted</span><span>no good LDS answer has been published</span></div><div><span class=\"badge v-contested\">Contested</span><span>they have a real answer — say so</span></div><div><span class=\"badge v-answered\">Answered</span><span>their answer wins, and we say so</span></div></div>"},
  {icon:"💬",title:"You are given the words",body:"Each case ends with a line you can say. Each one also has a <b>Conversation</b> tab with a real back-and-forth: they say this, you say that, they push back, you answer. Bible and Book of Mormon references open where you point at them, with the verses either side."},
  {icon:"🚀",title:"Where to start",body:"Read <b>The heart of it</b> first. It is one page, and it holds the three differences everything else hangs from. Then <b>Sharing Jesus</b>, which is about the person rather than the argument. Replay this tour any time from the sidebar.",cta:"Take me to the heart of it"}],
 islam:[
  {icon:"🔍",title:"What this is",body:"<b>__N__ documented claims</b> about Islam, each weighed against the Bible. Nearly all of it is argued from Islam's own trusted books — Sahih al-Bukhari, Sahih Muslim, and the classical commentaries. Not from ours. That is the whole method."},
  {icon:"📖",title:"Every case opens in plain English",body:"Short blocks. One idea per sentence. What Islam teaches, what the sources say, the strongest Muslim answer, how strong the case is, and one line to say out loud. The full sourced version sits underneath on the same page."},
  {icon:"🏷",title:"Four verdicts, one glance",body:"Every claim lands in one of four columns:<div class=\"vrow2\"><div><span class=\"badge v-admitted\">Admitted</span><span>the facts sit in Islam's own sources</span></div><div><span class=\"badge v-unrefuted\">Unrefuted</span><span>no good Muslim answer has been published</span></div><div><span class=\"badge v-contested\">Contested</span><span>they have a real answer — say so</span></div><div><span class=\"badge v-answered\">Answered</span><span>their answer wins, and we say so</span></div></div>"},
  {icon:"🤝",title:"Honour runs this conversation",body:"Never mock Muhammad or the Quran to a Muslim's face. It is heard as an attack on their family and it ends everything, permanently. Honest questions are always fine. Contempt never is. Six cases here exist only to tell Christians which arguments to drop."},
  {icon:"🚀",title:"Where to start",body:"Read <b>The heart of it</b>. Islam's whole case against Christianity rests on one claim, and that claim runs into the Quran itself. Master that and every other door opens. Replay this tour any time from the sidebar.",cta:"Take me to the heart of it"}],
 jw:[
  {icon:"🚪",title:"What this is",body:"<b>__N__ documented claims</b> about Jehovah's Witnesses, weighed against the Bible. Almost every fact is cited from the Watchtower's own publications, so a Witness can check it in their own library. Seven cases exist to tell Christians which arguments to drop."},
  {icon:"📖",title:"Every case opens in plain English",body:"Short blocks. One idea per sentence. What they teach, what the record shows, their best answer, how strong the case is, and one line to say at the door. The sourced version is underneath on the same page."},
  {icon:"🏷",title:"Four verdicts, one glance",body:"Every claim lands in one of four columns:<div class=\"vrow2\"><div><span class=\"badge v-admitted\">Admitted</span><span>their own publications concede it</span></div><div><span class=\"badge v-unrefuted\">Unrefuted</span><span>no good Watchtower answer exists</span></div><div><span class=\"badge v-contested\">Contested</span><span>they have a real answer — say so</span></div><div><span class=\"badge v-answered\">Answered</span><span>their answer wins, and we say so</span></div></div>"},
  {icon:"💔",title:"Remember what it costs them",body:"A Witness who agrees with you may lose their mother. Shunning is organised and it includes family. Say that out loud early — that you know what you are asking, and you are not asking them to pay it today. Nothing else you say lands until they believe you understand."},
  {icon:"🚀",title:"Where to start",body:"Read <b>The heart of it</b>. One date holds up everything else: 607 leads to 1914, which leads to 1919, which is the only basis for the Governing Body's authority. Pull the first link and the chain is on the floor.",cta:"Take me to the heart of it"}],
 bhi:[
  {icon:"🦁",title:"What this is",body:"<b>__N__ documented claims</b> taught in the Hebrew Israelite camps, weighed against the Bible. Where the camps are right, this site says so — and on the church's silence about slavery, they are right."},
  {icon:"🧩",title:"This is not one movement",body:"It runs from a church founded in 1896 by a man born enslaved, through a vegan farming town in Israel, to the street camps in the viral clips. They argue with each other, bitterly. Any argument that treats them as one thing fails at once, and deserves to."},
  {icon:"📖",title:"Every case opens in plain English",body:"Short blocks. One idea per sentence. What they teach, why it lands, what the text actually says, where they have a point, and one line to say. The full sourced version is underneath on the same page."},
  {icon:"🤲",title:"Concede before you answer",body:"Nearly every case here starts by granting what is true inside the claim. The church's long silence on slavery. The reality of the curses. The failure of cheap grace. That is not a trick. It is the only order in which any of this can be heard."},
  {icon:"🚀",title:"Where to start",body:"Read <b>The heart of it</b>. One chapter carries the whole movement — Deuteronomy 28. Read it from verse 1, then read chapter 30, where the same covenant promises the way back.",cta:"Take me to the heart of it"}],
 messiah:[
  {icon:"🕎",title:"This section runs in reverse",body:"The rest of this site weighs a religion against the Bible. Here the New Testament is not shared ground yet. So this section argues from the Hebrew Bible, the Targum and the Talmud — books your Jewish friend already holds. <b>__N__ cases</b>, each with the strongest Jewish reply."},
  {icon:"🕯",title:"Name the history first",body:"The Crusades. The blood libel. The expulsions. Luther. Then Christian Europe in 1941. That history is not background to this conversation. It is the room you are standing in. Say it yourself, unprompted, before you open a single verse."},
  {icon:"🏷",title:"Four verdicts, one glance",body:"Every case lands in one of four columns:<div class=\"vrow2\"><div><span class=\"badge v-admitted\">Conceded</span><span>Jewish sources grant it themselves</span></div><div><span class=\"badge v-unrefuted\">Strong</span><span>no good Jewish answer has been published</span></div><div><span class=\"badge v-contested\">Contested</span><span>argued both ways — say so</span></div><div><span class=\"badge v-answered\">Don't use</span><span>a Christian argument that fails</span></div></div>"},
  {icon:"💬",title:"One text, then listen",body:"Never stack twelve prophecies. It reads as a sales pitch and invites twelve rebuttals. Take one. Ask how they read it. Mean the question. Every case carries the counter-missionary reply, because your friend will have it ready."},
  {icon:"🚀",title:"Where to start",body:"Read <b>The heart of it</b>. Isaiah 53, and what the Targum and the Talmud said about it long before there was anything to argue about. It is the one argument made entirely from their own library.",cta:"Take me to the heart of it"}],
 god:[
  {icon:"🌌",title:"This section runs in reverse",body:"Nothing here is argued from the Bible's authority to someone who does not hold it. The case is built from sources that do not want the conclusion — skeptical historians, atheist philosophers, and the manuscript record. <b>__N__ cases</b>."},
  {icon:"🎯",title:"Who are you talking to?",body:"There are three different conversations. The <b>philosophical atheist</b> is rare, has real reasons, and enjoys the argument. The <b>apathetic none</b> is most people and is not looking for one. The <b>deconvert</b> has heard your best material already, often from someone they loved. Aiming the wrong one at the wrong person is the usual way this fails."},
  {icon:"🏷",title:"Four verdicts, one glance",body:"Every case lands in one of four columns:<div class=\"vrow2\"><div><span class=\"badge v-admitted\">Conceded</span><span>skeptical scholars grant it</span></div><div><span class=\"badge v-unrefuted\">Strong</span><span>no good answer has been published</span></div><div><span class=\"badge v-contested\">Contested</span><span>argued both ways — say so</span></div><div><span class=\"badge v-answered\">Don't use</span><span>a Christian argument that fails</span></div></div><p style='margin:10px 0 0'>A third of this section is marked Contested on purpose.</p>"},
  {icon:"🧨",title:"Read the retirement list first",body:"The banana. \"No transitional fossils.\" The second law of thermodynamics. Darwin's deathbed. Pascal's wager as an opener. Every one is still circulating, and every one tells a skeptic you do not check your sources. It is the highest-value page here."},
  {icon:"🚀",title:"Where to start",body:"Read <b>The heart of it</b>. Not \"the Bible says\", but what a room full of skeptical historians grants about AD 30 — and what explains it.",cta:"Take me to the heart of it"}]
};
const strip=t=>String(t).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');
console.log('new tour reading levels:');
for(const [k,steps] of Object.entries(T)){
  const r=g(strip(steps.map(s=>s.body).join(' ')));
  console.log('  '+k.padEnd(9)+'grade '+String(r.grade).padStart(5)+'  avg '+String(r.wps).padStart(5)+'w  longest '+r.longest+'w'+(r.grade>10?'  ▲':'  ✓'));
}
fs.writeFileSync('new-tours.json',JSON.stringify(T));
